{% set name = "language_tool_python" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/language_tool_python-{{ version }}.tar.gz
  sha256: 0067c7b583265c3b0cc21cf22a03075dae0853f6542646788f0be377d8ea0559

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ={{ python_min }}
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - tqdm
    - psutil
    - toml

test:
  imports:
    - language_tool_python
  commands:
    - pip check
  requires:
    - pip
    - python ={{ python_min }}

about:
  summary: Checks grammar using LanguageTool.
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
